Added basic expression converter.
semoro/kotlin pull request #1
Opened 2017-10-17 17:27 UTC by Dimach

2017-10-17 17:48 UTC, semoro reviewed
Clean for now

2017-10-17 17:48 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/JavaToJKTreeBuilder.kt
> +            throw RuntimeException("Not supported")
use `throw UnsupportedOperationException("Not supported")` if it's permament, or `TODO` if not

2017-10-17 17:48 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/JavaToJKTreeBuilder.kt
> +            if (this !is PsiLiteralExpressionImpl) {
Assert here is better

2017-10-17 17:48 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/JavaToJKTreeBuilder.kt
> +            if (this !is PsiLiteralExpressionImpl) {
But it will not work for Kotlin without effect system, so no problem here

2017-11-08 19:03 UTC, Knize approved these changes

2017-11-08 22:08 UTC, semoro requested changes
Please rebase onto latest nj2k branch and regenerate transformers

2017-11-20 11:54 UTC, semoro approved these changes

2017-11-20 11:54 UTC, merged