Random fixes
semoro/kotlin pull request #14
Opened 2018-08-07 04:12 UTC by semoro

DefaultArgumentsConversion
Temporary conversion for println

Support for new converter dedicated testData
Fix variables mutability processing
Expanded post-processings

2018-08-08 12:24 UTC, Dimach requested changes

2018-08-08 12:24 UTC, Dimach commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/DefaultArgumentsConversion.kt
> +                singleStatement.safeAs<JKExpressionStatement>()?.expression?.safeAs<JKMethodCallExpression>()
Support this.someCall() case.

2018-08-08 12:24 UTC, Dimach commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/DefaultArgumentsConversion.kt
> +                if (parameter.type.type != targetParameter.type.type) continue@checkMethod
Same as above.

2018-08-08 12:24 UTC, Dimach commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/DefaultArgumentsConversion.kt
> +            if (calledMethod.returnType.type != method.returnType.type) continue
Collapse thats if's to one.

2018-08-08 12:24 UTC, Dimach commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/DefaultArgumentsConversion.kt
> +                parameter.initializer = defaultValue
In defaultValue expression may be used other call argument. References must be updated.

2018-08-17 17:40 UTC, semoro commented
Merged manually

2018-08-17 17:40 UTC, closed without merging