Switch to when, break statements
semoro/kotlin pull request #18
Opened 2018-10-02 13:22 UTC by darthorimar

2018-10-31 13:34 UTC, semoro requested changes

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/NewCodeBuilder.kt
> +            printer.separated(", ", ktWhenCase.labels) {
renderList

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/NewCodeBuilder.kt
> +            if (statements.size == 1)
`statements.singleOrNull()?.accept...`

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/j.kt
> +class JKJavaDefaultwitchCaseImpl(statements: List<JKStatement>) : JKJavaDefaultwitchCase, JKBranchElementBase() {
Switch? Typo

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/j.kt
> +interface JKJavaDefaultwitchCase : JKJavaSwitchCase {
Switch? Typo

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/SwitchStatementConversion.kt
> +            else -> JKKtDefaultWhenLabelImpl()
`JKKtElseWhenLabel`

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/SwitchStatementConversion.kt
> +        val fallsThrough: Boolean = if (caseIndex == cases.lastIndex) {
`: Boolean` is redundant here

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/SwitchStatementConversion.kt
> +            when (psiStatement) {
`if (is 1, is 2 && psiS.canCompl...) return false`

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/SwitchStatementConversion.kt
> +        if (allowBlock && statementsToKeep.size == 1) {
TODO: Investigate in which cases we should unwrap internal block

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/base.kt
> +                    else -> TODO("Sth wrong")
`error` function, "Tree corrupted" message for ex

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/base.kt
> +                    child.detach(child.parent!!)
`.detach(this@deepClone)` to run consistency checks

2018-10-31 13:34 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/base.kt
> +                    it.detach(it.parent!!)
`.detach(this@deepClone)` to run consistency checks

2018-11-06 17:26 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/SwitchStatementConversion.kt
> +                .map { JKKtValueWhenLabelImpl(it.label) }
Isn't it will cause tree corruption without `it.invalidate()` ?

2018-11-06 19:53 UTC, darthorimar commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/SwitchStatementConversion.kt
> +                .map { JKKtValueWhenLabelImpl(it.label) }
No, because label was already detached on line 25

2018-11-13 12:01 UTC, semoro approved these changes

2018-11-13 12:51 UTC, merged