some fixes
semoro/kotlin pull request #20
Opened 2018-10-08 09:32 UTC by darthorimar

2018-10-31 15:15 UTC, semoro requested changes

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/InstanceofConversion.kt
> +                when (checkingType) {
Join this when with if on 24

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/NewCodeBuilder.kt
> +            for ((index, argument) in javaNewExpression.arguments.expressions.withIndex()) {
renderList

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/NewCodeBuilder.kt
> +        override fun visitMutabilityModifier(mutabilityModifier: JKMutabilityModifier) {
Fix also in `visitKtProperty`

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/FieldInitializersInPrimaryFromParamsConversion.kt
> +class FieldInitializersInPrimaryFromParamsConversion : TransformerBasedConversion() {
Please, use stateful MatchBasedConversion instead

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/ModifiersConversion.kt
> +        jkParameter.filterModifiers {
TODO: open is allowed on property-parameters, maybe handle in printer?

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/ModifiersConversion.kt
> +                jkParameter.modifierList.modifiers.find {
`any`

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/ConversionsRunner.kt
> +//            +InsertDefaultPrimaryConstructorConversion(context)
----

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/InsertDefaultPrimaryConstructorConversion.kt
>          if (element !is JKClass) return recurse(element)
Replace none with any on 18 to fix invalid application

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/FieldInitializersInPrimaryFromParamsConversion.kt
> +                parameter.modifierList = fieldDeclaration.modifierList.also { it.detach(it.parent!!) }
implement and use detached here

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/k.kt
> +    override var variableIdentifier: JKNameIdentifier by child(variableIdentifier)
Can be also a destructuring declaration, so maybe DeclarationStatement here?

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/LabeledStatementConversion.kt
> +    private fun isConvertedForLoopToWhileOne(blockStatement: JKBlockStatement): Boolean =
Special AST node for such converted elements

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/jk.kt
> +        private fun methodSymbolForToken(
Extract somewhere

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/conversions/ForConversion.kt
> +            val reversed = when ((operationType  as? JKJavaOperatorImpl)?.token?.token) {
psiToken maybe?

2018-10-31 15:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/symbols.kt
> +    val filedType: JKType
fieldType

2018-11-28 13:27 UTC, darthorimar commented
Closed due to https://github.com/semoro/kotlin/pull/22

2018-11-28 13:27 UTC, closed without merging