Simple code builder
semoro/kotlin pull request #5
Opened 2017-11-20 20:16 UTC by semoro

2017-11-20 21:55 UTC, Dimach requested changes

2017-11-20 21:55 UTC, Dimach commented on j2k/newSrc/org/jetbrains/kotlin/j2k/NewCodeBuilder.kt
> +            builder.append("/* !!! Hit visitElement !!! */")
Add element type here.

2017-11-20 23:37 UTC, Knize approved these changes

2017-11-28 11:34 UTC, Dimach approved these changes

2017-11-28 21:03 UTC, merged