Transform impls
semoro/kotlin pull request #6
Opened 2017-12-02 20:07 UTC by Knize

2017-12-03 08:12 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/jk.kt
> +class JKPostfixExpressionImpl(override var expression: JKExpression?,
Why made `expression` nullable?

2017-12-04 22:41 UTC, semoro requested changes

2017-12-04 22:41 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/jk.kt
> +class JKPostfixExpressionImpl(override var expression: JKExpression?,
OK, after discussion with @Dimach, we decided, that it shouldn't be nullable here, and in `JKPostfixExpression`, but should to in `JKUnaryExpression`

2017-12-04 22:43 UTC, Knize commented
OK

2018-02-05 21:15 UTC, semoro requested changes

2018-02-05 21:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/jk.kt
> -    val left: JKExpression
Why did interfaces change?

2018-02-05 21:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/j.kt
> -    val identifier: JKClassReference
Why those `val` became `var`? And other in this file

2018-02-05 21:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/jk.kt
> -class JKNameIdentifierImpl(override val name: String) : JKNameIdentifier, JKElementBase() {
This shouldn't be mutable

2018-02-05 21:15 UTC, semoro commented on j2k/newSrc/org/jetbrains/kotlin/j2k/tree/impl/j.kt
> -class JKJavaAccessModifierImpl(override val type: JKJavaAccessModifier.AccessModifierType) : JKJavaAccessModifier, JKElementBase() {
This shouldn't be mutable

2018-02-09 21:06 UTC, semoro approved these changes

2018-02-09 21:07 UTC, merged